spring:
  datasource:
    url: jdbc:h2:file:./data/testdb  # Change to 'jdbc:h2:mem:testdb' for in-memory database during development
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    # Connection pool settings (optional)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true  # Enables H2 Console for easy DB access
      path: /h2-console  # The path to access H2 console in your browser

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Use 'update' for automatic schema updates on each startup
    show-sql: true  # Show SQL queries in logs for debugging
    properties:
      hibernate:
        format_sql: true  # Format SQL in logs for better readability

  sql:
    init:
      mode: always  # Ensure that schema and data.sql are run every time the application starts

logging:
  level:
    org.springframework.jdbc: DEBUG  # Enable SQL logging for database operations
    org.springframework.boot.autoconfigure.sql.init: DEBUG  # Show SQL scripts initialization
    com.groww.growwclone.service.impl.StockServiceImpl: DEBUG  # Log stock update process for debugging
    org.springframework.web: DEBUG  # Enable HTTP request/response logging (optional, for API debugging)
    org.springframework.web.multipart.MultipartHttpServletRequest: TRACE  # Enable logging of file uploads
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
